### ISSUE TITLE
Add (or increase of exists) buffer

### ISSUE THREAD

**Issue by Arutaz** [icefields/Power-Ampache-2#158]
When playing (from Nextcloud music) and the connection is a bit crappy from time to time, the music stops to load for 1-2 seconds.

This seems to happen much more than when playing directly from Nextcloud web interface.

I think it would be good to add a buffer, or if there exists a buffer today, then increase the size of the buffer.

Maybe also preload the next 2-3 songs (like some other apps do).

**Comment by icefields** [comment]
hello, there's already buffer, song preload and gapless-play by default.
I'm not sure what can be wrong with your connection to Power Ampache 2 wihout seeing any log.

**Comment by Arutaz** [comment]
It's actually not realted to network, because it behaves the same at home with Wi-Fi (just tried).

I enabled debug logs, but I can't open any of them.

**Comment by icefields** [comment]
ok, can you tell me the exact model of the phone, the version of the app and where you downloaded from, and how to reproduce the bug. Does it happen often? all the time? some time?
thanks

**Comment by Arutaz** [comment]
Google Pixel 9 Pro XL, running GrapheneOS (latest version)

Latest version of Power Ampache 2 from F-droid (I think that is "Version 1.00-67-fdroid (67)")

It happens all the time. It plays a few seconds, then just start loading. Then plays a few seconds, then loading.

Sometimes when I choose a song to play, it starts to play a few seconds, then just starts playing another song.
Same thing if I try to jump ahead in a song, then it can sometimes starts to play another song.

I'm using Nextcloud with the Music app version 2.0.1

I don't get anything in the debug logs.

**Comment by tigermick** [comment]
Hi,
I have exactly the same problem randomly.
I have a pixel running GrapheneOS too and ampache2 1.00-68 from github release.

**Comment by icefields** [comment]
thanks @tigermick @Arutaz , I've been looking into the issue. @Arutaz you confirm you're also on Nextcloud? This seems to be an issue isolated to Nextcloud.

**Comment by tigermick** [comment]
I'm also using Nextcloud

**Comment by icefields** [comment]
I increased the buffer and lowered the memory used by the image cache. The updates are available in version 1.00-69
https://github.com/icefields/Power-Ampache-2/releases/tag/v1.00-69
give it a try please

**Comment by Arutaz** [comment]
I just tried it now.

It was looking promising for about 3-4 songs, then suddenly it started doing the same old thing where it starts to load, play a second, then load again repeatedly, and then suddenly it just changed to the next song by it self.

I'm using the 1.00-69 version from github (through Obtanium).

**Comment by tigermick** [comment]
Hi,
Exactly same observation for me.
It seems to work for few songs and same bug later...

**Comment by icefields** [comment]
ok, thanks for testing. Looks like the buffer increase helped but not fixed it. I could try to increase it even more. But it's odd that this happens only for Nextcloud users, is there something in nextcloud that limits its network output? Or something that slows it down?
I'll keep investigating.

**Comment by tigermick** [comment]
Sooner, I used ultrasonic app and no problem like this but in ultrasonic settings, I can choose number of songs preload (1 to 10 or illimited), time of buffer and size of buffer.
To don't have problem, i always choose illimited, 1 hour and 4GB.(big values).

**Comment by icefields** [comment]
ok, I'll be doubling the default buffers in the next release. After testing with these values over the past few days, it seems to perform smoothly, despite the increase. 
In the meantime, I'll begin exploring a solution to add advanced options, allowing users to manually adjust these values from the settings screen.

**Comment by philus88** [comment]
Hi, same here for me also with nextcloud.
What i have seen was at the time this happens the android device pulls a lot of traffic (network shows a big chunk of download)
It even takes out the browser if a webbrowser loads at the same time so i get a timeout on webbrowsing. Second later everythings fine
For me it looks like when this happens it tries to download or buffer e big chunk of stream data....
That's just my two cents

**Comment by icefields** [comment]
@philus88 Thank you for looking into the issue. I observed the same behavior, which is why I’ve been experimenting with buffer sizes. I found that on my debug server (which isn’t very powerful), the server restarts when the network traffic peaks, I even get kicked out from ssh sessions. I managed to resolve it by adjusting some network configurations, but since I’m using the original Ampache backend, I’m not sure how to apply similar fixes with Nextcloud.
Anyway, I plan to add advanced settings that will allow users to manually adjust the buffer sizes based on their specific needs and server capabilities.

**Comment by philus88** [comment]
If i got the time maybe i could find something in the nextcloud log, but i doubt it....
But its strange that the android app cloggs the network while this rebuffer or something happens...
Good luck hope you find something.
Because tempo (ampache client on github) has no such issues....but your app has a better "shuffle" ;)

**Comment by icefields** [comment]
@philus88 I know, it’s quite strange, especially since a server shouldn’t crash just because an app requests more data! For now, I have a large buffer in place to handle streaming under less-than-ideal network conditions, so the app constantly tries to fill it. Once I add buffer options in the advanced settings, users will be able to adjust them according to their needs. And after gaining some experience and receiving feedback, I’ll likely be able to create default presets for different types of servers (such as the original Ampache, Nextcloud, etc.).

I wouldn’t consider this a definitive fix, but here's what I did on my server to make things work. I adjusted the following values in the `apache2.conf`:

```
KeepAlive On
MaxKeepAliveRequests 400
KeepAliveTimeout 600
MaxClients 200
```

I also increased memory, upload size, post size, and similar parameters (though I don't remember all the details—I should have documented this better).

Additionally, I modified the service itself by running the command `systemctl edit apache2.service` and adding:

```
[Service]
Restart=always
LimitNOFILE=65535
```

I also made changes to `/etc/sysctl.conf`, but I’ll need to double-check the exact values later. Let me know if you're interested, and I can provide more details.
After making those changes on the server I haven't ran into that issue again.

**Comment by icefields** [comment]
I hope those settings that I added in the new version will take care of everyone's playback issues. Once version 1.00-70 is out, try to adjust buffer values. And please let me know which values work for you, I might add them as presets.


https://github.com/user-attachments/assets/0ede2824-466c-43e2-b450-acef4235c3cb

**Comment by tigermick** [comment]
Hi,
Thank you for all your efforts.
I tried several kind of settings but I can't find one which works well...
I always end up having the same problem ... 😭 very sorry

**Comment by icefields** [comment]
@tigermick no worries, I will keep an eye on the issue.
Can you try the following buffer settings? (don't forget to kill the app afterwards with the restart button in settings):
min buffer: max (100s)
max buffer: max (600s)
buffer for playback: 30s
buffer for playback after rebuffer: max (100s)
backbuffer: max (100s)

**Comment by icefields** [comment]
even more buffer options added, and new advanced player.

[You can try the new version using this link](https://github.com/icefields/Power-Ampache-2/releases/tag/v1.01-75), or wait for it to be available on F-Droid and the Play Store in a few days. Experiment with the buffer settings under "Player Advanced Settings." Additionally, check out the new advanced player, also found in the same menu.

**Comment by tigermick** [comment]
@icefields thank you very much !
I tried your previous settings and it worked better.
Now, I'm trying with the new settings and with the new advanced player and it seems to be better again for now. (I set up to max the 2 first settings)
I'm continuing to test 😉

**Comment by tigermick** [comment]
After to test a long time, sometimes approximately no problem and sometimes I have problem quickly whereas I am connected on the same network than my nextcloud server with wifi ...
I use powerampache2 on my personal et professional phone (galaxy A53 and Pixel 8a).
I noticed when i skip back to the previous music, powerampache2 seems to load like if it have to download again the mp3 ... When you play the next track, the previous track is removed in cache ?

**Comment by icefields** [comment]
@tigermick I’m not sure I fully understand the issue. Are you saying that after you download a song and play it, the app starts downloading it again when you go back to it? That doesn’t seem possible, as you would need to explicitly press the download button to initiate a download. I’ll check the behavior of the download button later, but I’m confident that once a song is downloaded, there’s no way for it to be downloaded again automatically.

To answer your second question, the previous song should automatically be removed from the cache, unless you’ve downloaded it. If it’s already downloaded, there shouldn’t be any loading, or it should be minimal. If you're streaming, the song will be retrieved again from the source.

**Comment by tigermick** [comment]
Sorry for my bad english ...
When you begin to play music with "tune spinner" button, I suppose your app start to download the tracks in the playslist (depending on the setting buffer rules)  in the cache memory ? and when a music finished, the player play the next music immediatly. But if you wanted to listen the previous track, you go back to it and player needs to download the mp3 file in cache again to play it ...
why do application remove music in the cache memory after playing it ?

And otherwise when I just start playing a playlist, I still have cuts after a random moment.

**Comment by icefields** [comment]
hey @tigermick , no worries, I understand now. I was a bit confused because the app has a dowload option, and also has cache and music buffer. Let me give you a quick explanation on how the buffer works.
When you start playing a playlist or an album, or tune spinner, the songs are cached in memory depending on the amount of buffer you set. That is correct.
Power Ampache 2 does not retain the buffer of the previous song once it's skipped forward or another track starts. The buffer is cleared for the song you are no longer playing.
If you skip back to the previous song, the player will re-buffer it from scratch, meaning the previous song is typically not cached in memory and will need to be reloaded.
Music players, especially on mobile with limited memory, typically discards the buffer of the previous song when you move on to another song. If you skip back, the player will start the buffering process from the beginning of the previous song again.
This is a standard behaviour, keeping already consumed buffer in memory would result in your ram filling very fast (I have 100MB flac songs for example, imagine keeping 3 of those in memory after playing them).
If you download the songs you can avoid the rebuffering when skipping back, since the song is already in your storage.
I hope this clarifies the confusion.
Thanks again for reporting potential bugs!

**Comment by tigermick** [comment]
Ok thanks for your precisions.
I tell you my experience with this example because when I used ultrasonic, all musics downloaded in cache stay in cache as long as the playslist don't change and I thought it was possible to have the same operation with your app.
In the meantime, when I listen a playlist with power ampache 2, at the beginning, it works well but after a random time, the music stops often to load for 1-2 seconds and sometimes it skips forward to the next music before end of current music ...

**Comment by icefields** [comment]
ok @tigermick , the other app that you're using might have a disc cache, because I don't think is possible to keep all that data in memory, if you have 10 flac songs of 100mb each, that'd be 1G of memory just to hold a cache of the previous songs. Even as a disc cache, that much cache doesn't sound ideal to me, but I could have it as an option in the future, that you will have to enable from settings. I will add the feature to my todo list.

About the interruptions, check the new version that I will release today, I cannot reproduce the issue but it might be caused by something that I fixed last week. Also try to use the advanced player, you can enable it from settings.

**Comment by icefields** [comment]
@tigermick I decided to implement the disc cache, I will add an option to settings to turn it on. I don't have an ETA right now, but I expect the feature to be released before the summer.

**Comment by icefields** [comment]
Next version will have disc cache, let's see if that does anything to your problems

**Comment by tigermick** [comment]
Hi,
Thank you for this feature !
But I have a problem again ...
It seems to be another problem ...
This my adb logcat about power ampache 2 : 
`NotificationProvider: Failed to load bitmap: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 500`
and after I can find this line : 
```
IPCThreadState: oneway function results for code 2 on binder at 0xd6f4fededc20 will be dropped but finished with status UNKNOWN_TRANSACTION
05-04 19:22:32.188 21941 22792 I IPCThreadState: oneway function results for code 1 on binder at 0xd6f4fededc20 will be dropped but finished with status UNKNOWN_TRANSACTION
05-04 19:22:32.689 21941 21941 I Choreographer: Skipped 93 frames!  The application may be doing too much work on its main thread.
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal: Playback error
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:864)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:836)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:105)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:232)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:317)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:85)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:   Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 500
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:310)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:88)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1109)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:453)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
05-04 19:22:33.907 21941 22074 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:1119)
05-04 19:22:37.079 21941 21941 I Choreographer: Skipped 259 frames!  The application may be doing too much work on its main thread.
05-04 19:22:37.110 21941 21941 W NotificationProvider: Failed to load bitmap: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 500
```
I don't understand, what's the problem .... a music can cut and go to next track or just can zap one or more track ...

**Comment by icefields** [comment]
@tigermick Have you tried the latest release? This looks suspiciosly like an issue that I fixed recently

**Comment by tigermick** [comment]
Hi,
Effectively, all works fine know !
Thank you very much !
